// Code generated by MockGen. DO NOT EDIT.
// Source: IRepo.go

// Package bonus is a generated GoMock package.
package bonus

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockIRepo is a mock of IRepo interface.
type MockIRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIRepoMockRecorder
}

// MockIRepoMockRecorder is the mock recorder for MockIRepo.
type MockIRepoMockRecorder struct {
	mock *MockIRepo
}

// NewMockIRepo creates a new mock instance.
func NewMockIRepo(ctrl *gomock.Controller) *MockIRepo {
	mock := &MockIRepo{ctrl: ctrl}
	mock.recorder = &MockIRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepo) EXPECT() *MockIRepoMockRecorder {
	return m.recorder
}

// CreateBonus mocks base method.
func (m *MockIRepo) CreateBonus(UserUUID uuid.UUID) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBonus", UserUUID)
	ret0, _ := ret[0].(int)
	return ret0
}

// CreateBonus indicates an expected call of CreateBonus.
func (mr *MockIRepoMockRecorder) CreateBonus(UserUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBonus", reflect.TypeOf((*MockIRepo)(nil).CreateBonus), UserUUID)
}

// GetBonus mocks base method.
func (m *MockIRepo) GetBonus(UserUUID uuid.UUID) (int, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBonus", UserUUID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// GetBonus indicates an expected call of GetBonus.
func (mr *MockIRepoMockRecorder) GetBonus(UserUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBonus", reflect.TypeOf((*MockIRepo)(nil).GetBonus), UserUUID)
}

// SetBonus mocks base method.
func (m *MockIRepo) SetBonus(UserUUID uuid.UUID, Extra int) (int, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBonus", UserUUID, Extra)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// SetBonus indicates an expected call of SetBonus.
func (mr *MockIRepoMockRecorder) SetBonus(UserUUID, Extra interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBonus", reflect.TypeOf((*MockIRepo)(nil).SetBonus), UserUUID, Extra)
}
