// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonDccd6943DecodeRsoiKpKTLHInternalModels(in *jlexer.Lexer, out *Airport) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "airport_uuid":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.AirportUUID).UnmarshalText(data))
			}
		case "name":
			out.Name = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDccd6943EncodeRsoiKpKTLHInternalModels(out *jwriter.Writer, in Airport) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"airport_uuid\":"
		out.RawString(prefix[1:])
		out.RawText((in.AirportUUID).MarshalText())
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Airport) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDccd6943EncodeRsoiKpKTLHInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Airport) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDccd6943EncodeRsoiKpKTLHInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Airport) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDccd6943DecodeRsoiKpKTLHInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Airport) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDccd6943DecodeRsoiKpKTLHInternalModels(l, v)
}
