// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson1690906cDecodeRsoiKpKTLHInternalModels(in *jlexer.Lexer, out *Bonus) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "user_uuid":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.UserUUID).UnmarshalText(data))
			}
		case "balance":
			out.Balance = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1690906cEncodeRsoiKpKTLHInternalModels(out *jwriter.Writer, in Bonus) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user_uuid\":"
		out.RawString(prefix[1:])
		out.RawText((in.UserUUID).MarshalText())
	}
	{
		const prefix string = ",\"balance\":"
		out.RawString(prefix)
		out.Int(int(in.Balance))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Bonus) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1690906cEncodeRsoiKpKTLHInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Bonus) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1690906cEncodeRsoiKpKTLHInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Bonus) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1690906cDecodeRsoiKpKTLHInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Bonus) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1690906cDecodeRsoiKpKTLHInternalModels(l, v)
}
