// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson47107b8bDecodeRsoiKpKTLHInternalModels(in *jlexer.Lexer, out *Promo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "promo_uuid":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.PromoUUID).UnmarshalText(data))
			}
		case "is_active":
			out.IsActive = bool(in.Bool())
		case "factor":
			out.Factor = float32(in.Float32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson47107b8bEncodeRsoiKpKTLHInternalModels(out *jwriter.Writer, in Promo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"promo_uuid\":"
		out.RawString(prefix[1:])
		out.RawText((in.PromoUUID).MarshalText())
	}
	{
		const prefix string = ",\"is_active\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsActive))
	}
	{
		const prefix string = ",\"factor\":"
		out.RawString(prefix)
		out.Float32(float32(in.Factor))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Promo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson47107b8bEncodeRsoiKpKTLHInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Promo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson47107b8bEncodeRsoiKpKTLHInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Promo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson47107b8bDecodeRsoiKpKTLHInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Promo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson47107b8bDecodeRsoiKpKTLHInternalModels(l, v)
}
