// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonBd361432DecodeRsoiKpKTLHInternalModels(in *jlexer.Lexer, out *Report) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ticket_uuid":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.TicketUUID).UnmarshalText(data))
			}
		case "flight_uuid":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.FlightUUID).UnmarshalText(data))
			}
		case "user_uuid":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.UserUUID).UnmarshalText(data))
			}
		case "state":
			out.State = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBd361432EncodeRsoiKpKTLHInternalModels(out *jwriter.Writer, in Report) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ticket_uuid\":"
		out.RawString(prefix[1:])
		out.RawText((in.TicketUUID).MarshalText())
	}
	{
		const prefix string = ",\"flight_uuid\":"
		out.RawString(prefix)
		out.RawText((in.FlightUUID).MarshalText())
	}
	{
		const prefix string = ",\"user_uuid\":"
		out.RawString(prefix)
		out.RawText((in.UserUUID).MarshalText())
	}
	if in.State != "" {
		const prefix string = ",\"state\":"
		out.RawString(prefix)
		out.String(string(in.State))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Report) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBd361432EncodeRsoiKpKTLHInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Report) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBd361432EncodeRsoiKpKTLHInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Report) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBd361432DecodeRsoiKpKTLHInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Report) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBd361432DecodeRsoiKpKTLHInternalModels(l, v)
}
