// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB39c1f48DecodeRSOICWInternalModels(in *jlexer.Lexer, out *Ticket) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ticket_uuid":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.TicketUUID).UnmarshalText(data))
			}
		case "flight_uuid":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.FlightUUID).UnmarshalText(data))
			}
		case "user_uuid":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.UserUUID).UnmarshalText(data))
			}
		case "date":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Date).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB39c1f48EncodeRSOICWInternalModels(out *jwriter.Writer, in Ticket) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ticket_uuid\":"
		out.RawString(prefix[1:])
		out.RawText((in.TicketUUID).MarshalText())
	}
	{
		const prefix string = ",\"flight_uuid\":"
		out.RawString(prefix)
		out.RawText((in.FlightUUID).MarshalText())
	}
	{
		const prefix string = ",\"user_uuid\":"
		out.RawString(prefix)
		out.RawText((in.UserUUID).MarshalText())
	}
	{
		const prefix string = ",\"date\":"
		out.RawString(prefix)
		out.Raw((in.Date).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Ticket) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB39c1f48EncodeRSOICWInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Ticket) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB39c1f48EncodeRSOICWInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Ticket) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB39c1f48DecodeRSOICWInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Ticket) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB39c1f48DecodeRSOICWInternalModels(l, v)
}
