// Code generated by MockGen. DO NOT EDIT.
// Source: IRepo.go

// Package report is a generated GoMock package.
package report

import (
	models "RSOI_CW/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIRepo is a mock of IRepo interface.
type MockIRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIRepoMockRecorder
}

// MockIRepoMockRecorder is the mock recorder for MockIRepo.
type MockIRepoMockRecorder struct {
	mock *MockIRepo
}

// NewMockIRepo creates a new mock instance.
func NewMockIRepo(ctrl *gomock.Controller) *MockIRepo {
	mock := &MockIRepo{ctrl: ctrl}
	mock.recorder = &MockIRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepo) EXPECT() *MockIRepoMockRecorder {
	return m.recorder
}

// AddStat mocks base method.
func (m *MockIRepo) AddStat(report models.Report) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddStat", report)
	ret0, _ := ret[0].(int)
	return ret0
}

// AddStat indicates an expected call of AddStat.
func (mr *MockIRepoMockRecorder) AddStat(report interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddStat", reflect.TypeOf((*MockIRepo)(nil).AddStat), report)
}

// CheckByUsers mocks base method.
func (m *MockIRepo) CheckByUsers() ([]models.ReportUsers, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckByUsers")
	ret0, _ := ret[0].([]models.ReportUsers)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// CheckByUsers indicates an expected call of CheckByUsers.
func (mr *MockIRepoMockRecorder) CheckByUsers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckByUsers", reflect.TypeOf((*MockIRepo)(nil).CheckByUsers))
}

// GetFilling mocks base method.
func (m *MockIRepo) GetFilling() ([]models.ReportFilling, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilling")
	ret0, _ := ret[0].([]models.ReportFilling)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// GetFilling indicates an expected call of GetFilling.
func (mr *MockIRepoMockRecorder) GetFilling() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilling", reflect.TypeOf((*MockIRepo)(nil).GetFilling))
}
